// Location: HEADER
export const MENU = "MENU"
export const IS_SEARCH_BOX_ACTIVE = "IS_SEARCH_BOX_ACTIVE"
export const SEARCH_BOX_VALUE = "SEARCH_BOX_VALUE"
export const RESET_SEARCH_BOX_VALUE = "RESET_SEARCH_BOX_VALUE"
